stages:
  - build
  - integration_test
  - acceptance_test
  - cleanup

building:
  stage: build
  script: 
    - echo "Building..."
    - source /opt/ros/melodic/setup.bash
    - catkin_make run_tests
    - xsltproc -o unit_tests.html gtest-result.xsl build/test_results/primary/gtest-primary_controller_unit_tests.xml
  artifacts:
    paths:
    - unit_tests.html
    expire_in: 1 week

integration_testing:
  stage: integration_test
  script: echo "Integration Testing..."

acceptance_testing:
  stage: acceptance_test
  script: echo "Acceptance Testing..."

pages:
  stage: cleanup
  script:
    - mkdir public
    - mv unit_tests.html public
  artifacts:
    paths:
      - public