stages:
  - build
  - unit_test
  - integration_test
  - acceptance_test
  - cleanup

before_script:
  - source source_ros.bash
  - source $ROS_SOURCE_BASH_FILE

building:
  stage: build
  script: 
    - echo "Building..."
    - catkin_make 

unit_testing:
  stage: unit_test
  script: 
    - echo "Unit Testing..."
    - catkin_make run_tests --cmake-args -DBUILD_UNIT_TESTS=ON -DBUILD_INTEGRATION_TESTS=OFF
    - xsltproc -o unit_tests.html gtest-result.xsl build/test_results/primary/gtest-primary_controller_unit_tests.xml
  artifacts:
    paths:
    - unit_tests.html
    expire_in: 1 week

integration_testing:
  stage: integration_test
  script:
    - echo "Integration Tests..."
    - catkin_make run_tests --cmake-args -DBUILD_UNIT_TESTS=OFF -DBUILD_INTEGRATION_TESTS=ON
    - xsltproc -o integration_tests.html gtest-result.xsl build/test_results/primary/rosunit-primary_controller_integration_tests.xml
  artifacts:
    paths:
    - integration_tests.html
    expire_in: 1 week    

acceptance_testing:
  stage: acceptance_test
  script: echo "Acceptance Testing..."

pages:
  stage: cleanup
  script:
    - mv unit_tests.html public
    - mv integration_tests.html public
  artifacts:
    paths:
      - public
